id: PD45D35AE
initial_creation_type: input
source_metadata:
  title: Mipham Rinpoche Series
  language: pt
  description: 'Texts by and about the great Nyingma polymath Jamgön Mipham Namgyal
    Gyatso (mi pham rnam rgyal rgya mtsho, 1846-1912), arguably the most influential
    Tibetan scholar of recent times:'
  volume:
    b3731c2e31014fd58a95d752d6922ad7:
      title: Advice for Beginners
      parent: Advice
    1e9ecc8c3c96439db59b2bbcc200a361:
      title: Advice to Jigme Tenpe Nyima
      parent: Advice
    8b756938fb984b6f8cb5dd1f87615006:
      title: Essence of the 84000 Approaches to the Dharma
      parent: Advice
    4d6f9d30c816434db63f629fc8eb9f8e:
      title: How to Cultivate Concentration
      parent: Advice
    897ff964550c459ba95430a263d17a4a:
      title: Profound Instruction on Śamatha
      parent: Advice
    08b63093a4ca4c90b9c6a8b87535e1a9:
      title: Satirical Advice for the Four Schools
      parent: Advice
    6646994800424e82874f68f56ea07762:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    bb97ee07d84f452782351cc02db6162b:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    db600644ef594b5cb78ce1fe97493438:
      title: The Perfect Equality of the Dharmadhātu
      parent: Advice
    877c6f062e2e4e6a9efacfb82be0fd98:
      title: A Brief Prayer for Summoning Prosperity
      parent: Aspiration Prayers
    500707dc1fcb4639a9397c47901d9a56:
      title: Aspiration for the Four Activities
      parent: Aspiration Prayers
    7c1f00dad37c4e30a50af210d9ea5e7b:
      title: Light Offering Prayer
      parent: Aspiration Prayers
    b3e51d5ca1544878ae3dcff2599e042a:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers
    488fd00607c94dd1ac461ec83b2c160a:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Aspiration Prayers
    90e851d8ff554170b8477650a4696440:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
    7c6432b1039741789ac68362c808b6d4:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Aspiration Prayers
    771f06f994804d94b7190c2d54b0ba08:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Aspiration Prayers
    dc8c4b044f1f477dbe1e2f5ad18d8a95:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Averting Obstacles
    46a789c1312d4b25ac9ed4200313e2e7:
      title: Benedictory Verses for A Brilliant Elucidation of Logical Reasoning
      parent: Benedictory Verses
    313c2245f81148d78fd666fd8a807651:
      title: Benedictory Verses for White Lotus
      parent: Benedictory Verses
    dee2f14104f245c7b84c4c308472b3db:
      title: Ascertaining the Two Kinds of Selflessness
      parent: Buddhist Philosophy
    281e781358d24c448afa22040c1d04a8:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Buddhist Philosophy
    6d2c397df3834be397f9494a9b6cbd50:
      title: 'Gateway to Learning: Individual Selflessness'
      parent: Buddhist Philosophy
    460428fa4574418a8ebde684c4dd3792:
      title: Profound Instruction on the View of the Middle Way
      parent: Buddhist Philosophy
    b9f8d4e26e3941e29e917aab6ea2e807:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      parent: Buddhist Philosophy
    37240443461247dfa667f09b6cf580d9:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      parent: Buddhist Philosophy
    a45ce869d4a04777b036846878416f71:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      parent: Buddhist Philosophy
    2f9327ded70e46f8b826fe220a3c5ebb:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      parent: Buddhist Philosophy
    f1bc68172af040a0b1887f4cd184464e:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    a4c5abdc87384620860fa788e6fd7d7f:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Dharma Protectors
    0ba889fe39d74763afcd529532c21ca3:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Dharma Protectors
    b0e0bde0a8714ded8533af0dddb2aef5:
      title: Brief Offering Prayer to Za Rāhula
      parent: Dharma Protectors
    a83be83ef0b04df889141c4df02387a4:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Dharma Protectors
    01bf2f30466a4353b72be293106206f2:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Dharma Protectors
    fda1c866922d4984983e3275a31040af:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Dzogchen
    b422256ed40442adacc044099648cc9d:
      title: Pith Instruction on the Three Crucial Statements
      parent: Dzogchen
    a7cf08d643ca4229ade1014d4fd5ce3c:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    71d121fd61b64f1791bc14553f1acfce:
      title: The Essence of Mind
      parent: Dzogchen
    852910e635f8444f8a6b5e7c9ec0b9c7:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Dzogchen
    a84ab3e2c1bc4bbb8bf6ae1f40e8b989:
      title: The Key Points of Trekchö
      parent: Dzogchen
    34c48ec3927f4c67aebae04d2a551b8a:
      title: The Nature of Mind
      parent: Dzogchen
    eb98066c8b354c8d9ecb5671ec06627f:
      title: Brief Gesar Windhorse Invocation
      parent: Gesar
    c0ce7e0e302c4c83996d5ecc66de153a:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    80a6f861dfa7475ab3fe352fa2fcf9d6:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Gesar
    e4eee0b76bf346399529f37f6f52abe1:
      title: Prayer to Gesar
      parent: Gesar
    ad77927bffe5490eb6e201c7410ade8c:
      title: Short Windhorse Prayer to Gesar
      parent: Gesar
    0059e8d9d44e473c9b381ccfebde578c:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Gesar
    309c5e273feb45f89c4d86bb3df52900:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Gesar
    5658d3e469814d4b943276950d05036e:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Gesar
    dd204fe134434cc39b73aac77bd1a02f:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Gesar
    4d8e299141054d19a16600d03a167d0a:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    b9e1187527924366b493502ad9062b15:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    4e71e08eb7624bffa3eadf3aa82c4b2e:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Guru Yoga
    ba9c4c2c19b24bca8a539275a4291f92:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Guru Yoga
    fb9cc800cbb743a5979e2606a4643a48:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    e10d55af2ea443e4b4c92be6b690a058:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    1a4dcced4f1f45deac37774d23790ffb:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Guru Yoga
    9c737c6087e7440799d28d26163a945f:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    af319152d44d4b68b420e56b2bf314b3:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    73eb0a97ea0c4b96b9f9e67e92e198f2:
      title: Short Torma Offering to Kurukullā
      parent: Kurukullā
    ada721d0007c4a29b55a5d65a2cfe4e1:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    615f347c6900424faf9c2ab58bce5add:
      title: Brief Dzogchen Lineage Prayer
      parent: Lineage Prayers
    68977a20785049c6beba6281d28b89e9:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    b58f0d9ad45c4a22825318baf7a74e09:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    2d52a7aa47de4d0e96a460ce4f54376b:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Longevity
    532ea905df134ea39a7f197a797dd4bd:
      title: Brief Windhorse Invocation
      parent: Lungta
    46f9854aa9c44987a9d280f3806793e9:
      title: Daily Lungta Recitation
      parent: Lungta
    475b8f0ed6cb470a821690a2182cb93a:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Lungta
    11ba9d583bb14300bfeee69a9d99af70:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    4474f304a83d484f8740f928b20b81a1:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    dad13e4267e5477f8f8c6fe05d592a7d:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Offering
    7c6f288f246a4862beb6a171db94c6f4:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    d1b01957cee942a786f77b2b10ad35fe:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Praise
    4fd44b8ac8fb4cd1947eb76cd7e22c3e:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Praise
    535c55f54fdf4e3fbe96a484bb3ee995:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Praise
    6e3642ca40214170b7a756eab9ccac0f:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      parent: Prayers
    65dceafb75d24200be70430aaec73d75:
      title: Prayer to Akṣobhya
      parent: Prayers
    2a1dac86a8c447488944d114123a447f:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
    ddc5e6c18dd54e47861b58bd2c7a326c:
      title: Three Prayers from the Earth Pig Year
      parent: Prayers
    9c05e72c6db4484ea352f02e16ff88f1:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    7aea8c72cadd4862886e7f752f247c00:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Prayers to Guru Rinpoche
    5f251c11d55b4ec3ac2cfe57eff004f9:
      title: Recollecting the Deeds of The Tenth Days
      parent: Prayers to Guru Rinpoche
    0c54d8f745dd4b22987a09ed975abbd7:
      title: The Prayer which is the Source of All True Realization
      parent: Prayers to Guru Rinpoche
    f687c5779e7d4915aefa23c9a51d6a77:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Prayers to Mañjuśrī
    cc74b0cac61945e6bd8deae25ef15833:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Prayers to Mañjuśrī
    1aa673b3295649c8aa1f3e05823effb0:
      title: In Praise of the Protector Mañjughoṣa
      parent: Prayers to Mañjuśrī
    180ff5c0b99040af8af57be0bbb77c19:
      title: Prayer to Mañjuśrī
      parent: Prayers to Mañjuśrī
    661678b30718463287b4287789372aeb:
      title: Prayer to the Sovereign of Dharma and Retinue
      parent: Prayers to Śākyamuni
    abdc9c543017480886c451c381e99e52:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
    81641f164f934c5d9ab729f241d99921:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      parent: Preliminary Practice
    ba61f8ac5bc74ad0b5083dd78f623399:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    a5c8e6d5ca79473f9278310351f18977:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    27924e078f1c4cf490ef57481f51fe85:
      title: A Sādhana of Sitātapatrā
      parent: Sādhanas
    911944813c41494795f3a7847cd054ce:
      title: A Sādhana of White Sarasvatī
      parent: Sādhanas
    8560db0a981f401e9ffd86735936dc79:
      title: Acala Sādhana
      parent: Sādhanas
    2a61b2d2162345d8a72b13d1e008a118:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
    4fbae2f857cb44e89aead5dc43de1a4e:
      title: Sādhana of Mārīcī
      parent: Sādhanas
    fac90a61eca4494abc2b33b29fd9c4d0:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Sādhanas
    dc1deaef02f042aaae05e6e808519d1a:
      title: Brief Sang Offering
      parent: Sang Offering
    ad7bedc092954bb7af6f7abf3d292e95:
      title: Brief Sang Offering to Purify Contamination
      parent: Sang Offering
    f7b3072bd52c4da7b10f3d2dab74a285:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Saving Lives
    023ce33d390f4c43ba1a2976ee9398cd:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    1a18bd43090649d8a20e994f6be22043:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    84373a47677e4761be1e083328be118f:
      title: Prayer to Tārā, Combined with Her Mantra
      parent: Tārā
    4ca8f00ac11b49dc8ccd6cf5fa30d3bb:
      title: Outline of the Ten Royal Sūtras
      parent: Topical Outlines
    2777908081884ddd8cd7d631a422eb04:
      title: Concise Tsok Feast
      parent: Tsok
    6de973ccd96a4f5492e6b935ce4a5694:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Tsok
    26ce011101784c6a91de71b0f46944e6:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Vajrasattva
created_at: '2022-03-01T00:57:12.460243'
last_modified_at: '2022-03-01T00:57:12.460246'
